title: Song Zhuoran'sPersonal introduction
page-top-title: Song Zhuoran
top-section-bg-text: We Shall Never Surrender.
home-subtitle: Song Zhuoran&ensp;|&ensp;宋卓然
copyright-text: '&copy; Song Zhuoran 2024-2025. All Rights Reserved.'
